### ISSUE TITLE
Error switching simMode

### ISSUE THREAD

**Issue by thingnl** [nomorecoin/tAPIbot#2]
After running sucsesful tests, changed simMode to False.
When starting receiving this error message:
Traceback (most recent call last):
  File "Application.py", line 40, in <module>
    runLoop()
  File "Application.py", line 23, in runLoop
    trader.update() 
  File "/home/x56304/tAPIbot/tapi/trader.py", line 63, in update
    self.determinePosition()
  File "/home/x56304/tAPIbot/tapi/trader.py", line 85, in determinePosition
    balShort = self.tradeData['funds'].get(shortCur,0)
UnboundLocalError: local variable 'shortCur' referenced before assignment

Currency pair is cnc_btc
longOn = btc

python version:

> > > import sys
> > > print sys.version
> > > 2.7.3 (default, Jan  2 2013, 13:56:14) 
> > > [GCC 4.7.2]

pylab is loaded.

Any solution of work around available?

**Comment by thingnl** [comment]
Duh..... figured it out myself....

longOn should be first or second.... not ltc or btc or whatever you are traiding.....

soz to bother you.....
